name: cardscratcher
description: Freelance for mehdi and Mohamed Ahmed made by Fahmi Barguellil and Firass Hamed.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_signin_button: ^1.1.0
  scratcher: "^1.4.0"
  google_sign_in: ^4.5.4
  http: ^0.12.2
  flutter_login: ^1.0.14
  font_awesome_flutter: 8.7.0

  confetti: ^0.5.4+1

  marquee_flutter: ^0.1.4

  flash: "^1.2.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3


  # Smart project structure with dependency injection and route management
  flutter_modular: ^2.0.0+1

  # Allow acces to streamBuilder
  rxdart: ^0.24.1

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^2.0.1

  # Providing a cross-platform 'dart:html' to avoid compilation failure when targeting mobile
  universal_html: ^1.2.3

  # Powerful Http client for Dart
  dio: ^3.0.10

  # Providing a persistent store for simple data.
  shared_preferences: ^0.5.8

  # Provides a cross-platform (iOS, Android) API to request permissions and check their status
  permission_handler: ^5.0.1+1

  # Package to handle dynamic String & Json interpolation.
  interpolation: ^1.0.1

  # Better conversion of ENUMs to string - It also can handle converting back again!
  enum_to_string: ^1.0.9

  # Provides internationalization and localization facilities
  intl: ^0.16.1

  # Overrides == and hashCode so you don't have to waste your time writing boilerplate code.
  equatable: ^1.2.3

  # Plugin for launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: ^5.5.0

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^0.18.0

  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: 0.6.7+4

  # Flutter library to load and cache network images.
  cached_network_image: ^2.2.0+1

  # Adds support for google fonts
  google_fonts: ^1.1.0

  # To make items slidable
  flutter_slidable: ^0.5.5

  firebase_admob: ^0.9.3+4

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

  # An opiniated, community-driven set of lint rules for Dart and Flutter projects.
  lint: ^1.2.0

  # Performs static analysis of Dart code.
  analyzer: ^0.39.17

  # A mock framework inspired by Mockito.
  mockito: ^4.1.1

  # Automatically generates native code for adding splash screens in Android and iOS.
  flutter_native_splash: ^0.1.9

  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.7.5

# flutter_native_splash plugin config
# run the package with flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: "assets/images/logo.png"
  android_disable_fullscreen: true
  color: "E4EEF5"

# flutter_launcher_icons plugin config
# run the package with flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

  # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
